sonar.projectKey=ridesense-ai
sonar.projectName=RideSense AI
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests

sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8